# Generated by Django 5.2.7 on 2026-02-25 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='pharmacy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.pharmacy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='app1.pharmacy'),
        ),
        migrations.AddField(
            model_name='debtor',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.pharmacy'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='pharmacy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='app1.pharmacy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='app1.pharmacy'),
        ),
    ]
