# Generated by Django 5.2.7 on 2026-02-25 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alert_pharmacy_customer_pharmacy_debtor_pharmacy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='app1.pharmacy'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.pharmacy'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='app1.pharmacy'),
        ),
    ]
